version: "3.9"

services:
  db:
    image: postgres:15
    container_name: forum_db
    restart: always
    environment:
      - POSTGRES_DB=comments_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jdth,fath
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: forum_backend
    command: >
      sh -c "python comments_app/manage.py migrate &&
             python comments_app/manage.py collectstatic --noinput &&
             gunicorn comments_app.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: forum_frontend
    ports:
      - "5173:5173"
    restart: always

volumes:
  postgres_data:
